### ISSUE TITLE
swagger-api路径问题

### ISSUE THREAD

**Issue by lw5946** [dyc87112/swagger-butler#10]
你好，我使用你的代码没什么问题。但是有个问题想向您请假下。

根据我对您代码的理解，聚合的时候，是在返回SwaggerResources集合时，设置了每一个微服务的api-docs地址，且获取所有路由之后再直接替换（如：替换后是 `/service-a/v2/api-docs`），这样再通过网关请求的时候，会路由到每一个微服务对应的api-docs接口地址，但是每一个api-docs内部的接口地址怎么加上路由地址的前缀呢（如：/service-a），这样才能从网关路由到对应的微服务。

我使用你的代码，看到swagger-ui界面请求的时候是自动加上路由前缀了的，是在源码哪里去做的这个操作呢？这种操作应该跟网关无关吧，我是用的spring-cloud-gateway。

期待您的解答，谢谢！

**Comment by lw5946** [comment]
哦，因为接口的地址都是相对路径，所以当文档的地址改变了，接口的地址就对应的有那个前缀了，对吗？

**Comment by flyingglass** [comment]
Spring Cloud Gateway 也能集成？
